<a href="https://colab.research.google.com/github/ronel-meli/DSA-Python/blob/main/Airplane_Crashes_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

167249-Obosi Eliud Odhiambo
189806-Meli Ronel Chepchirchir

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("saurograndi/airplane-crashes-since-1908")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'airplane-crashes-since-1908' dataset.
Path to dataset files: /kaggle/input/airplane-crashes-since-1908

In [2]:
import kagglehub
import pandas as pd
import os

# Download latest version
path = kagglehub.dataset_download("saurograndi/airplane-crashes-since-1908")
print("Path to dataset files:", path)

# Use the path variable to find and load the CSV
csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]
file_path = os.path.join(path, csv_files[0])

# Load it as a DataFrame
df = pd.read_csv(file_path)

# Preview the data
df.head()

Using Colab cache for faster access to the 'airplane-crashes-since-1908' dataset.
Path to dataset files: /kaggle/input/airplane-crashes-since-1908

,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
0,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,2.0,1.0,0.0,"During a demonstration flight, a U.S. Army fly..."
1,07/12/1912,06:30,"AtlantiCity, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,5.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...
2,08/06/1913,NaN,"Victoria, British Columbia, Canada",Private,-,NaN,Curtiss seaplane,NaN,NaN,1.0,1.0,0.0,The first fatal airplane accident in Canada oc...
3,09/09/1913,18:30,Over the North Sea,Military - German Navy,NaN,NaN,Zeppelin L-1 (airship),NaN,NaN,20.0,14.0,0.0,The airship flew into a thunderstorm and encou...
4,10/17/1913,10:30,"Near Johannisthal, Germany",Military - German Navy,NaN,NaN,Zeppelin L-2 (airship),NaN,NaN,30.0,30.0,0.0,Hydrogen gas which was being vented was sucked...

Determine the number of rows and columns in the dataset.

In [3]:
row, column=df.shape
print("Number of rows")
print(row)
print("Number of columns")
print(column)

Number of rows
5268
Number of columns
13

Display the last 75 rows in the dataset.

In [4]:
df.tail(75)

,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
5193,03/15/2008,08:15,"Nbagu, Nigeria",Trade Wings Aviation Ltd.,NaN,Lagos - Bebi Air Strip,Beechcraft 1900D,5N-JAH,UE-322,3.0,3.0,0.0,The plane crashed while en route. Wreckage was...
5194,04/03/2008,11:00,"Lawa, Suriname",Blue Wing Airlines,NaN,Paramaribo - Lawa,Antonov An-28,PZ-TSO,1AJ007-17,19.0,19.0,0.0,While attempting to land the crew aborted the ...
5195,04/09/2008,23:27,"Bundeena, Australia",Avtex Air Services,NaN,Sydney - Brisbane,Swearingen SA227AC Metroliner III,VH-OZA,AC-600,1.0,1.0,0.0,The pilot of the mail plane reported some mino...
5196,04/11/2008,22:15,"Chrisinau, Moldova",Kata Transportation,NaN,"Chrisinau, Moldova - Antalya, Turkey - Sudan",Antonov An-32,ST-AZL,3009,8.0,8.0,0.0,Just minutes after the take off the plane trie...
5197,04/15/2008,14:30,"Goma, Congo",Hewa Bora Airways,NaN,Goma - Kisangani - Kinshasa,McDonnell Douglas DC-9-51,9Q-CHN,47731,85.0,0.0,47.0,"While attempting to takeoff, the plane failed ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5263,05/20/2009,06:30,"Near Madiun, Indonesia",Military - Indonesian Air Force,NaN,Jakarta - Maduin,Lockheed C-130 Hercules,A-1325,1982,112.0,98.0,2.0,"While on approach, the military transport cras..."
5264,05/26/2009,NaN,"Near Isiro, DemocratiRepubliCongo",Service Air,NaN,Goma - Isiro,Antonov An-26,9Q-CSA,5005,4.0,4.0,NaN,The cargo plane crashed while on approach to I...
5265,06/01/2009,00:15,"AtlantiOcean, 570 miles northeast of Natal, Br...",Air France,447,Rio de Janeiro - Paris,Airbus A330-203,F-GZCP,660,228.0,228.0,0.0,The Airbus went missing over the AtlantiOcean ...
5266,06/07/2009,08:30,"Near Port Hope Simpson, Newfoundland, Canada",Strait Air,NaN,Lourdes de BlanSablon - Port Hope Simpson,Britten-Norman BN-2A-27 Islander,C-FJJR,424,1.0,1.0,0.0,The air ambulance crashed into hills while att...
5267,06/08/2009,NaN,"State of Arunachal Pradesh, India",Military - Indian Air Force,NaN,Mechuka for Jorhat,Antonov An-32,NaN,NaN,13.0,13.0,0.0,The military transport went missing while en r...

Each column except the first one has some missing data. For each column, name
the most appropriate method for treating the missing data

a) Operator, Route ,Type and Location should be filled with 'unknown' because they are all dummy variables, and dropping rows with missing values would discard them

b)Flight ,Registration and cn/In will be left as Nan or labled 'Non Specified' ,The above are unique identifiers that cannot be estimated or imputed accurately

c)Time: Fill with a placeholder 'Unknown'
Time of day is recorded as a string format and cannot be mathematically averaged or interpolated. Using a placeholder retains the record for day-level analysis without inventing false times.

d)Aboard and Fatalities: Impute using the column Median example ;or group-based median by aircraft Type
These are continuous or discrete count variables. The median is preferred over the mean because aviation accidents feature extreme outliers, which would heavily distort a mean-based imputation ,have missing data.

e)Ground is filled with 0-
 In historical crash reporting, missing ground casualty data almost universally implies that zero people on the ground were killed or injured. Leaving it blank distorts calculations, whereas filling with zero accurately reflects historical recording habits.



1.   List item
2.   List item

import matplotlib.pyplot as plt
import seaborn as sns

top25 = (
    top_100_fatalities
    .groupby('State/Country')['Fatalities']
    .sum()
    .sort_values(ascending=False)
    .head(25)
)

plt.figure(figsize=(10,10))
colors = sns.color_palette('pastel', len(top25))

plt.pie(
    top25,
    labels=top25.index,
    autopct='%1.1f%%',
    colors=colors,
    startangle=90,
    textprops={'fontsize': 8}
)

plt.title('Top 25 Countries/U.S. States by Number of Fatalities')
plt.axis('equal')
plt.tight_layout()
plt.show()